### ISSUE TITLE
Mixed float / int operators cast the wrong way

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#13]
The following pixel shader:

float4 PixelMain(float a : TEXCOORD0) : SV_Target
{
	float b = 1 - a;
	return b;
}

Gives the following result:

#version 130

in float xsc_vary_TEXCOORD0;

out vec4 SV_Target0;

void main()
{
    float b = float(1 - int(xsc_vary_TEXCOORD0));
    SV_Target0 = b;
}

It casts the texcoord into int instead of converting 1 to float.

**Comment by LukasBanana** [comment]
This is indeed a problem of the translation from HLSL's implicit casts to GLSL explicit casts, because GLSL only supports very restricted implicit casts.
Currently the right-hand-side of a binary expression is casted to match the type of the left-hand-side.
I think a function which determines the best suitable types for a binary expression should do the trick.

**Comment by LukasBanana** [comment]
I continued with the translation of implicit conversions, and your code works now (but this is not the end of the story).

Here is the current example I use:
```
float4 VS(float x : TEXCOORD0) : SV_Position
{
    float  a = 1 + 1;
    float  b = 2 + x;
    float  c = 3.0 + x;
    float  d = x + 4;
    float  e = 5;
    float  f = -6 + x;
    float3 g = 3 + 1.5;
    float3 h = 1 + g + 2;
    float3 i = h*2.0;
    float3 j = h*2;
    float3 k = h+2.0;
    float3 l = h+2;
    return 1;
}
```
And this is the GLSL output:
```
#version 130

in float x;

void main()
{
    float a = float(1 + 1);
    float b = 2.0 + x;
    float c = 3.0 + x;
    float d = x + 4.0;
    float e = 5.0;
    float f = float(-6) + x;
    vec3 g = vec3(3.0 + 1.5);
    vec3 h = vec3(1) + g + vec3(2);
    vec3 i = h * 2.0;
    vec3 j = h * 2.0;
    vec3 k = h + vec3(2.0);
    vec3 l = h + vec3(2);
    gl_Position = vec4(1);
}
```
