### ISSUE TITLE
GLSL auto version issue

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#14]
If the following pixel shader

float4 PixelMain(float4 color : COLOR) : SV_Target
{
    return color;
}

is compiled with Explicit Binding enabled, its result is

#version 130

in vec4 xsc_vary_COLOR;

layout(location = 0) out vec4 SV_Target0;

void main()
{
    SV_Target0 = xsc_vary_COLOR;
}

This GLSL version is wrong, and the resulting shader will not compile.

Note, this is a minor issue for me, because I can easily force the GLSL version.
I just reported it so it's not getting forgotten

**Comment by LukasBanana** [comment]
Thanks for the report, this might be an issue from the `GLSLExtensionAgent`.
I'm aware of a similar problem, but I didn't have the time to fix it yet.
As you mentioned, this can currently be avoided by forcing the GLSL version explicitly.

**Comment by LukasBanana** [comment]
Solved with [7fc960c2f7b4f6f599209e15a8d15d87e53d12f4](https://github.com/LukasBanana/XShaderCompiler/commit/7fc960c2f7b4f6f599209e15a8d15d87e53d12f4)
