### ISSUE TITLE
Geometry shader writes to output after EmitVertex();

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#15]
Look at the attached geometry shader example.
Also attached is the output of translation.

[GeomTest.hlsl.txt](https://github.com/LukasBanana/XShaderCompiler/files/764647/GeomTest.hlsl.txt)
[GeomTest.GSMain.geom.txt](https://github.com/LukasBanana/XShaderCompiler/files/764651/GeomTest.GSMain.geom.txt)

Notice that EmitVertex(); calls appear before the output values (eg. gl_Position) are written.
This will not work.

**Comment by LukasBanana** [comment]
I know, the geometry shaders are (just like the tessellation shaders) still in a very unreliable state.

**Comment by LukasBanana** [comment]
There were a lot of corner cases in your example, but it should be compilable now with the latest commit [020816b37a3b4916b954bb527ba226eb979c6e4c](https://github.com/LukasBanana/XShaderCompiler/commit/020816b37a3b4916b954bb527ba226eb979c6e4c)

Using multiple instances (or arrays) of the output structure is still a tricky case for the compiler (i.e. "GSOutput vertex[6]" in your example).
It's much simpler when only a single instance is used, and the "Append" intrinsics are not called in one large bunch at the end of the entry point.
