### ISSUE TITLE
Geometry shader SV_Position input error

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#16]
The following Geometry Shader:

struct VSOutput 
{
	float4 Position : SV_Position;
};

struct GSOutput 
{
	float4 Position : SV_Position;
};

[maxvertexcount(2)]
void GSMain(line VSOutput input[2], inout LineStream<GSOutput> stream)
{
	GSOutput o;
	
	o.Position = input[0].Position;
	stream.Append(o);

	o.Position = input[1].Position;
	stream.Append(o);
}

gets translated to:

#version 150

layout(lines) in;
layout(line_strip, max_vertices = 2) out;

void main()
{
    gl_Position = gl_Position;
    EmitVertex();
    gl_Position = gl_Position;
    EmitVertex();
}

The input should be gl_in[0].gl_Position / gl_in[1].gl_Position

That being said I was finally able to workaround all the geometry shader issues and write all my shaders so it compiles to GLSL and works correctly. Yay!

**Comment by LukasBanana** [comment]
Ah yes, "gl_in[]" is currently never written by the GLSL generator.
I'll put it on my ToDo list.

**Comment by LukasBanana** [comment]
Fixed with [a1db37df23084c160d6cacc172b8ac5f62cd39bf](https://github.com/LukasBanana/XShaderCompiler/commit/a1db37df23084c160d6cacc172b8ac5f62cd39bf)
