### ISSUE TITLE
Xsc::CompileShader accept strings instead of stream

### ISSUE THREAD

**Issue by amerkoleci** [LukasBanana/XShaderCompiler#2]
Is possible to have CompileShader and ShaderInput and ShaderOutput accept strings instead of streams?
I want to compile on runtime without access file system.

Thanks

**Comment by ongamex** [comment]
The ShaderInput structure uses "std::istream" for input, which is compatible with std::stringstream, so I guess you could create a std::stringstream and then cast it to std::istream.

**Comment by LukasBanana** [comment]
Use std::stringstream and call the member function 'str()' which returns an atd::string.
The shell does it this way as well, and only uses an ofstream when compilation succeeded.
