### ISSUE TITLE
Regression: automatically-guessed type of symbol

### ISSUE THREAD

**Issue by cybik** [LukasBanana/XShaderCompiler#24]
Yesterday, with some tinkering, all the shaders were translated correctly. Today 

- xsc failed to deduce the type of a variable called input, of type Input, declared as the entrypoint's argument
- xsc failed to deduce the type of an int counter that was declared in the for loop enclosing it

**Comment by LukasBanana** [comment]
Could you please give a code example or at least a code snippet.
The only thing about your points, that have changed, are:
* `input` and `output` are reserved keywords in GLSL, but Xsc will rename them properly on demand.
* Scope rules in for loops are different between HLSL and GLSL, but Xsc renames respective variables on demand.

**Comment by LukasBanana** [comment]
Is there still an issue about this in the current master branch?
Otherwise, I'm going to close this ticket.

**Comment by cybik** [comment]
I'll test tonight.

**Comment by cybik** [comment]
I think this was fixed? Didn't encounter them yesterday.
