### ISSUE TITLE
Validation issue: non-const with const assignment

### ISSUE THREAD

**Issue by cybik** [LukasBanana/XShaderCompiler#25]
This is invalid code when it tries to pass validation:
`const bool bMirrored = (NormalMirrorFlip.x < 0.0);`
as it references a uniform (NormalMirrorFlip.x). 

Can the generation process take this into account and *not* const all the things when either operand of an assignment is not a hard value?

**Comment by LukasBanana** [comment]
I don't understand your issue, since this translates just fine:
HLSL: `const bool bMirrored = (NormalMirrorFlip.x < 0.0);`
GLSL: `const bool bMirrored = (float(NormalMirrorFlip) < 0.0);`

**Comment by cybik** [comment]
If using GLSL 3.30 (#version 330), `const bool bMirrored = (float(NormalMirrorFlip) < 0.0);` does not validate.

**Comment by LukasBanana** [comment]
Ah yes, thanks for the hint. As stated [here](https://www.khronos.org/opengl/wiki/Type_Qualifier_(GLSL)#Constant_qualifier), GLSL only allows `const` objects being initialized with a constant expression, if the GLSL version is below 420.
I think it's the best to simply remove the `const` qualifier for the GLSL output, with versions before 420.

**Comment by cybik** [comment]
So that's what it was. Thanks for finding the root cause! :D

**Comment by LukasBanana** [comment]
Fixed with [4b7e898](https://github.com/LukasBanana/XShaderCompiler/commit/4b7e8984ce6d0f002d6ee5f16315e52b6bb02904)
