### ISSUE TITLE
Some vertex semantics doesn't work

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#28]
I got around to test the vertex semantics stuff you integrated back in 0.06 and it looks like it doesn't always work. Here's a test:
```hlsl
struct VSInput 
{
	float3 Position : POSITION;
	float4 Color : COLOR;
	float2 TexCoord0 : TEXCOORD0;
};

struct VSOutput 
{
	float4 Position : SV_Position;
	float4 Color : COLOR;
	float2 TexCoord0 : TEXCOORD0;
};

VSOutput VSMain(VSInput i)
{
	VSOutput o;

	o.Position = i.Position;
	o.Color = i.Color;
	o.TexCoord0 = i.TexCoord0;

	return o; 
}
```

When I compile it with the following command:

xsc.exe -E VSMain -T vert -EB -SPOSITION=0 -SCOLOR=4 -STEXCOORD0=5 VSTest.hlsl

I get the following output:

```glsl
// GLSL Vertex Shader "VSMain"
// Generated by XShaderCompiler
// 26/03/2017 16:57:07

#version 130

                     in vec3 Position;
                     in vec4 Color;
layout(location = 5) in vec2 TexCoord0;

out vec4 xsv_COLOR0;
out vec2 xsv_TEXCOORD0;

void main()
{
    gl_Position = vec4(Position);
    xsv_COLOR0 = Color;
    xsv_TEXCOORD0 = TexCoord0;
}
```

Vertex semantics is working for TexCoord but not for Position or Color.
I don't know what went wrong it worked in my version (which I'm still using)

**Comment by LukasBanana** [comment]
First of all, please surround your code examples with ``` to highlight the code, which makes it easier to read your code snippet (see more details about it [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/)).

About your issue: you have to use the full semantic name, which is `POSITION0`, _not_ `POSITION`, and `COLOR0`, _not_ `COLOR`.

**EDIT:**
The index number is always implied, if not set explicitly. The indexing works exactly like in the Microsoft compiler, but I derived the rules by trial and error:
- All digits on the right side of the semantic are used for index.
- If there are no digits on the right side of the semantic, the index 0 is used.
- Leading zeros are truncated.
- Sermantics are case insensitive, but the output is always upper case.

Examples:
- `Position` becomes `POSITION0` (i.e. Index 0).
- `Position001` becomes `POSITION1` (i.e. Index 1).
- `world02pos03` becomes `WORLD02POS3` (i.e. Index 3).

**Comment by Hyp-X** [comment]
Thank you, it works with 0-s added.
Sorry for the trouble
