### ISSUE TITLE
Preprocessing error with macro with parameters

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#3]
Hi,

I started evaluating this promising program to see if I could use it in my little engine.
(I tested 0.03 so this might have been fixed in latest.)
I seem to have found an issue with macro processing.

My code contains a macro with parameters, like this:

#define VSIN(name) i.name

Then there's this define

#define VS_START VSOUT VSMain(VSIN i) { VSOUT o;

Judging by the error message I got, VS_START expands to:

VSOUT VSMain(VSINi) { VSOUT o;

I think the preprocessor might be confused by the VSIN token which it cannot macro expand because it doesn't have parameters.
This somehow makes the whitespace after the token disappear.

Here's a test with a .cmd to run the command:
https://dl.dropboxusercontent.com/u/47279321/ShaderTest.zip

It prints:

`syntax error (DebugDraw.hlsl:20:19) : unexpected token: ')' (expected: identifier)`
`VSOUT VSMain(VSINi) { VSOUT o;`

**Comment by LukasBanana** [comment]
Thanks for this info, I'll take a look at this issue as soon as possible (but at the earliest tomorrow). To see the full pre-processed output use the "-PP" or "--preprocess-only" option for the command-line tool, or the "Options::preprocessOnly" member for the library.

**Comment by LukasBanana** [comment]
I fixed the bug in the pre-processor (see [Commit 908](https://github.com/LukasBanana/XShaderCompiler/commit/42001083e78bca375ba578f48947229e2c0b3b24)), now your shader example is compilable to GLSL. Build the project or wait for the release of 0.04-alpha.
Greetings,
Lukas
