### ISSUE TITLE
Preprocessor issue with #if/#elif/#else/#endif

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#4]
Hi,

Thanks for the Xsc Debugger, it's very useful for quickly testing features.

Copy the following into Xsc Debugger:

`#define FOO 1
#define BAR 0

float4 VSMain(float3 i : POSITION) : SV_Position
{
#if FOO    
    float3 position = i;
#elif BAR    
    float3 position = i;
#else
    float3 position = i;
#endif
    return float4(i, 1);
}`

It fails to compile with an "already defined" error.
(It would also be useful to be able to copy the error message from Xsc Debugger ...)

Looks like both the #if FOO and the #else section gets compiled in.

**Comment by LukasBanana** [comment]
Thanks again for your help. I currently wonder what I was doing at this point :-/
I think this needs a little more investigation than the previous bug.

**Comment by LukasBanana** [comment]
I fixed the bug in [Commit 914](https://github.com/LukasBanana/XShaderCompiler/commit/04ae6622d83f4d332d58b06b7b0dbb5b2519644a).
