### ISSUE TITLE
Request: Sampler objects for GL.

### ISSUE THREAD

**Issue by slembcke** [LukasBanana/XShaderCompiler#57]
What is the reason for restricting the use of sampler objects to Vulkan? I've used them in GL 3.3 before, but admittedly I don't understand what's new in Vulkan that would make them incompatible with the GL version.

There are a couple places where they would be "nice to have", but not actually necessary for my current project.

**Comment by LukasBanana** [comment]
What do you mean with sampler objects? I only know the `sampler` keyword (don't confuse with `sampler2D`) from the Vulkan GLSL variant, specified by the [`GL_KHR_vulkan_glsl`](https://www.khronos.org/registry/vulkan/specs/misc/GL_KHR_vulkan_glsl.txt) extension.
And there the _shader-combining of separate textures and samplers_ is declared as a new feature only available for Vulkan: like `sampler2D(textureObj, samplerObj)`.

Maybe you can post a code sample of what you mentioned that you've used in GL 3.3.

**Comment by slembcke** [comment]
Hrm. No, sorry I'm getting my graphics APIs all mixed up. :-\

I was thinking of this extension: https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_sampler_objects.txt, but it only applies when binding texture units, not as something mixable and matchable in GLSL. I could swear I've done it in GL before, but I'm clearly confusing myself with Metal SL...

**Comment by LukasBanana** [comment]
You can separate samplers and textures in OpenGL, but unfortunately not in GLSL, except for Vulkan.
