### ISSUE TITLE
Varibles packing

### ISSUE THREAD

**Issue by zillemarco** [LukasBanana/XShaderCompiler#59]
Hi, love this project and I'm planning to use it inside my own engine :)
One nice thing that could be added is variable packing to speed up their transition from the engine to the shaders (basically gouping the variables together as uniform buffers on the GLSL side).

Is this something that could be done?

Thank you very much, really appreciate what you are doing :)

**Comment by LukasBanana** [comment]
Do you mean packing variables of the old `uniform` notation into a single `cbuffer` like fxc does it with the `$Params` cbuffer?

Like from this:
```hlsl
uniform float4 ambient;
uniform float4 diffuse;
```
... to this:
```glsl
layout(std140) uniform Params {
    vec4 ambient;
    vec4 diffuse;
};
```
That would be a good idea indeed.

**Comment by zillemarco** [comment]
Yes exactly that :)
Also, but it is much harder, packing something like this

```hlsl
float2 alpha;
float beta;
float gamma;
```

into this

```glsl
uniform vec4 composite; // And this has composite.xy equals to alpha, composite.z equals to beta and composite.w equals to gamma
```

Obviously this would need a lot of work to the reflection because I need to know which uniforms have been packed togheter.

As I said, this I think will be much harder to implement, but it's an idea :)

**Comment by LukasBanana** [comment]
I think this kind of high-level packing is something the shader programmer should care about.
The XShaderCompiler was intended to make source-to-source translation only and not further optimizations.
If the input shader is not very efficient, the output shader wont't be more efficient either.

So grouping single uniforms into one constant buffer is a good idea, but I think transforming multiple variables into one is beyond the scope of this source-to-source compiler.

**Comment by zillemarco** [comment]
Ok, I understand your point and I agree, it was just an idea :)
That level of optimization could be achieved adding another tool to optimize the code (like glslOptimizer) so yeah, grouping uniforms would be more than enough :)

**Comment by LukasBanana** [comment]
Due to another request for this feature, I started with an approach in [329cb1c](https://github.com/LukasBanana/XShaderCompiler/commit/329cb1ca5838827715eafe8550ed12dd3278a917).
To reduce the number of open tickets, feel free to join the latest discussion in [Issue #87](https://github.com/LukasBanana/XShaderCompiler/issues/87).
