### ISSUE TITLE
Support for Shader Model 6.0?

### ISSUE THREAD

**Issue by ghost** [LukasBanana/XShaderCompiler#62]
Mostly functions and types in these extensions. 
https://khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_ballot.txt
https://khronos.org/registry/OpenGL/extensions/ARB/ARB_shader_group_vote.txt
https://khronos.org/registry/OpenGL/extensions/AMD/AMD_gpu_shader_half_float.txt
https://khronos.org/registry/OpenGL/extensions/AMD/AMD_gpu_shader_int16.txt

Will support of Shader Model 6.0 for compiler?

**Comment by LukasBanana** [comment]
I never used the extensions you mentioned and SM 6.0 is currently still in development as far as I know,
because the new DirectXShaderCompiler is not done yet.
So to answer your question, I currently have no specific plans when and how to implement SM 6.0 support.

**Comment by elviras9t** [comment]
In Vulkan API 1.1 already added subgroup operations, and 16-bit (8-bit) storage extensions.
