### ISSUE TITLE
"countbits" issue

### ISSUE THREAD

**Issue by ghost** [LukasBanana/XShaderCompiler#64]
I also found issue with latest GLSL. I found issue with a counting of bits. This function just skipping. Also need means, that uint64 does not support directly `bitCount` in GLSL, but can be calculated by unpacking and count bits from vector components. 

https://msdn.microsoft.com/en-us/library/windows/desktop/ff471355(v=vs.85).aspx
-->
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/bitCount.xhtml

**Comment by LukasBanana** [comment]
It seems that neither `countbits` in HLSL nor `bitCount` in GLSL support uint64, so what exactly is the issue?
I mean, the functions look pretty much identical for me.

**Comment by ghost** [comment]
Problem that `countbits` is missing in compiler.

**Comment by LukasBanana** [comment]
Thanks for the hint, the mapping for `countbits` was indeed empty in the GLSL backend.
Fixed it with [5f7bea6](https://github.com/LukasBanana/XShaderCompiler/commit/5443814b38ada73c2c6e17ad2b83929aac7f99b7).
