### ISSUE TITLE
ESSL #version 300 es

### ISSUE THREAD

**Issue by mlomb** [LukasBanana/XShaderCompiler#66]
The preprocessor directive #version in ESSL 3.0 should have the 'es'.
Currently when targeting ESSL300, ESSL310 and ESSL320 the preprocessor is set to '#version 300'.
It should be '#version 300 es'.

Reference: “#version 300 es” must appear in the first line of a shader program written in GLSL ES version 3.00." [Source](https://www.khronos.org/files/opengles3-quick-reference-card.pdf)

**Comment by LukasBanana** [comment]
Thanks for the hint. I'll take care of it.

**Comment by LukasBanana** [comment]
Fixed with [6cd87fb](https://github.com/LukasBanana/XShaderCompiler/commit/6cd87fb1e7068909a4ddaf9737736aba69ce73da).
