### ISSUE TITLE
HLSLAnalyzer::AnalyzeEntryPointParameterInOut(...) can't handle array parameter

### ISSUE THREAD

**Issue by Hyp-X** [LukasBanana/XShaderCompiler#7]
Try the following GS source:

struct VSOUT
{
    float3 Position : POSITION;
};

struct GSOUT
{
    float3 Position : POSITION;
};

[maxvertexcount(2)]
void GSMain(line VSOUT i[2], inout LineStream<GSOUT> stream)
{
	GSOUT p;
	p.Position = i[0].Position;
	stream.Append(p);
	p.Position = i[1].Position;
	stream.Append(p);
}

It will display the following error:

in 'void GSMain(VSOUT i[], buffer stream)':
context error (TestGS.hlsl:12:24) : missing semantic in parameter 'i' of entry point
void GSMain(line VSOUT i[2], inout LineStream<GSOUT> stream)
                       ^
analyzing input code failed

This is because a HLSLAnalyzer::AnalyzeEntryPointParameterInOut(...) doesn't handle the case where the parameter is an array.

I started writing code for handling ArrayTypeDenoter but I realized that I'm not sure how you want to handle things (see my previous issue) so I'll wait for an answer there.
Handling this input parameter here allows to go through and actually generate GS output.

**Comment by LukasBanana** [comment]
I currently try to find a solution for this, but while testing your sample HLSL code in the "AMD GPU ShaderAnalyzer" (which uses the D3Dcomiler), it looks like this is not valid HLSL code.
I get the following error:
`ERROR 0:12: error X3000: syntax error: unexpected token 'stream'`

**EDIT:**
The main entry point should look like this:
`void GSMain(line VSOUT i[2], inout LineStream<GSOUT> stream)`

**Comment by LukasBanana** [comment]
[Commit 936](https://github.com/LukasBanana/XShaderCompiler/commit/8027711dce01f1e112632ef5fb9845a3858f7c9e) should fix this issue.
