### ISSUE TITLE
"invalid class intrinsic 'tex2D' for global function call"

### ISSUE THREAD

**Issue by slembcke** [LukasBanana/XShaderCompiler#71]
Happens whenever there is a call to tex2D. Tried replacing it with other versions and they seem broken too.

I did a git bisect and tracked the issue down to 46d6ededc41b3edbb92ef457010b3f3128867b0a Will look into it a bit myself and see if I can figure out what those tables are for.

By the way, thank you for this project. I played with it a little a couple months ago in a toy project. Now that I finally have time to start my new game, I think I'll use it. The -Nforce-semantics option is exactly what I need for targeting GL 3.3, and spirv-cross doesn't do anything like that. :D

**Comment by slembcke** [comment]
Aha, looks like the enum got reordered, transpose and trunc got moved before the tex* ones and now the values are all discombobulated. Making a pull request shortly.

edit: #72

**Comment by LukasBanana** [comment]
Thank you, I've merged your pull request.
