### ISSUE TITLE
dynamic macro support?

### ISSUE THREAD

**Issue by ZeroKill1024** [LukasBanana/XShaderCompiler#79]
Sometimes macro definition maybe generated at runtime, when use such as shader template implement by macros.
I have read code source, but does't found this function. Is this here? or need to be implemented?
For example add: ShaderInput.dynamicMacros.push_back(Macro)

**Comment by LukasBanana** [comment]
Take a look how the Xsc [Shell](https://github.com/LukasBanana/XShaderCompiler/blob/master/src/Shell/Shell.cpp#L223) does this with the `-D<IDENT>` command (from line 224 to 241).
Just insert the source code of a macro definition to the input source stream.

**Comment by ZeroKill1024** [comment]
oh, yes, that is what i need, thank you.

**Comment by LukasBanana** [comment]
Great, so I can close this ticket.
Greetings,
Lukas
