### ISSUE TITLE
xsc does not report errors via return code

### ISSUE THREAD

**Issue by rgthomas** [LukasBanana/XShaderCompiler#80]
I'm using xsc to translate a bunch of HLSL shaders. Currently, it's difficult to tell if translation has succeeded within a script because xsc always returns 0. It would be super useful if xsc used it's return code to report when compilation/validation/whatever has failed by returning something other than 0. I have local changes to make it do this for the class of failures that I care about, but I'd be willing to help add this feature in a less hacky way if that's something you're interested in.

Thanks!

**Comment by LukasBanana** [comment]
Have you compiled the Xsc project yourself, or do you use the pre-compiled binaries?
In case of the former: it shouldn't be so difficult to add this to the `Shell/Main.cpp` file.

So far, I never used the return code anywhere.
I always thought of it as a return code if the program terminates abnormally (like when `abort()` is called).

**Comment by rgthomas** [comment]
I'm using a local build, and have it added locally to Main.cpp and several other files. The return code is useful for me because I want to have a python script that runs a bunch of shaders through translation & validation, and then reports back which ones succeeded and failed. We're also using translated shaders as a basis for the Nintendo Switch version of our shaders, and I want to have some different command line options for xsc in those cases, so using a script to handle "driving" xsc is really useful.

gcc, for example, returns '1' when compilation fails. I might use other return codes as well, but for the quick test I just did it returned 1.

If you'd like, I can send you a CL with my changes and you can tell me how you'd like it implemented, since my current local implementation is just a hack.

Thanks!

**Comment by LukasBanana** [comment]
Ok, how you'd like to send me your CL?
Or why not just creating a fork on Github?

**Comment by rgthomas** [comment]
Yeah, I'll create a fork and submit a PR for you to comment on. I haven't used git or Github in about three years so I'll probably have to wait until this weekend when I'll have some time to refresh myself on how to do that correctly :)

**Comment by LukasBanana** [comment]
I think this is solved by your [pull request](https://github.com/LukasBanana/XShaderCompiler/pull/81).
