### ISSUE TITLE
Oddity when using an Input's variables in a define

### ISSUE THREAD

**Issue by cybik** [LukasBanana/XShaderCompiler#82]
I'm not sure if this will make sense, but here we go.

```
#include "stuff.h"
struct Input
{
	float4 thing : SV_POSITION;
	float2 OtherThing : TEXCOORD0;
};

[stuff]

float4 main(Input input) : SV_TARGET
{
	float4 output = float4(0,0,0,1);
	float3 src = TEX2DLOD(Frame, float4(input.OtherThing, 0, 0)).rgb;

	float3 luminance = otherMethodInA(src);
[...]
	return output;
}

```

In the above context, `xsc` will not convert the shader, and will explode with:

```
2 ERRORS
--------
code generation error (../../shaders/directx9/AShader.psh:xx:yy) : missing array prefix expression for input/output semantic 'OtherThing'
			tex2Dlod(Frame, (float4(input.OtherThing, 0.0f, 0.0f)));
			                       ^~~~~~~~~
generating output code failed
compilation failed
```

But assigning `input.OtherThing` to a `float2`, and using that new `float2`, will just work.

**Comment by LukasBanana** [comment]
Can you please show the definition of the macro or function `TEX2DLOD`?
Otherwise, I don't know how to reproduce the issue.

**Comment by cybik** [comment]
Looks like this:
```
#define TEX2DLOD(name, uv)												\
			tex2Dlod(name, (uv))
```

**Comment by LukasBanana** [comment]
This seems to be a bug indeed. Thanks for pointing it out. I'll try to find out what's happening here.

**Comment by cybik** [comment]
Thank *you* for doing all of this!

**Comment by LukasBanana** [comment]
Should be fixed with [e8704c4](https://github.com/LukasBanana/XShaderCompiler/commit/e8704c4ea75453b1941af9811d56580fd5c0219c).
Let me know if it works now.

**Comment by cybik** [comment]
Pulling and testing, one moment.

**Comment by cybik** [comment]
Closing, **fixed**

Thanks!
