### ISSUE TITLE
Feature request: Option to add all uniforms to a uniform block

### ISSUE THREAD

**Issue by moradin** [LukasBanana/XShaderCompiler#87]
The compiler I'm working with expects all uniforms (except for images and samplers) to be in a uniform block. It would be great if there would be an option to support this.
If you are not planning on supporting this maybe you could give me some pointers as to how I could add it myself.

**Comment by LukasBanana** [comment]
This has already been requested, but in a slightly more complex way: [Issue #59](https://github.com/LukasBanana/XShaderCompiler/issues/59).
I think this one shouldn't be too complicated. Maybe I can make up a first approach at the weekend.

**Comment by moradin** [comment]
It looks like that discussion also ended on saying that creating the uniform block would be enough. If you do end up attempting it on the weekend I won't be around to test it but I would love to have something on Monday.

**Comment by LukasBanana** [comment]
That would kill two birds with one stone.
But I can't make any promises.
I'll see what I can do, though.

**Comment by LukasBanana** [comment]
I started with this in [329cb1c](https://github.com/LukasBanana/XShaderCompiler/commit/329cb1ca5838827715eafe8550ed12dd3278a917).
I left something to do, but I'm too tired to continue right now.
I'll let this issue open until I finally completed it.

**Comment by moradin** [comment]
I could try the current state today but I also use the STL-export-fix branch so I won't be able to get this until that is merged

**Comment by LukasBanana** [comment]
Take a closer look at the [commit history](https://github.com/LukasBanana/XShaderCompiler/network), it already is merged into the STL-export-fix branch.

**Comment by moradin** [comment]
Awesome, thx!

**Comment by moradin** [comment]
Sorry for the huge delay I had a lot of other tasks I needed to deal with. I just tried this packing on the STL-fix branch and the CompileShader function returns false. I don't see any log in the output but it looks like I need to implement a logger for windows with OutputDebugString.

**Comment by moradin** [comment]
Looks like I'm getting this error:
code generation error : GLSL extension 'GL_ARB_shading_language_420pack' or shader output version 'GLSL 4.20' required (for explicit binding slot)

**Comment by moradin** [comment]
I figured out that I need to allow extensions for this to work. I'm not sure if this is a good idea in general or maybe this case should be handled special but at least I can proceed this way.

**Comment by moradin** [comment]
Looks like the shader reflection data is also changed to just having one constant buffer which is understandable but I can't see any way to get reflection for the content of this buffer which I really need. Since the reflection also doesn't provide other crucial data for my case I will be probably adding more feature requests.

**Comment by LukasBanana** [comment]
Extensions only have to be enabled if you set the shader output to a fixed GLSL version. You can use the generic output version [`Xsc::OutputShaderVersion::GLSL`](https://github.com/LukasBanana/XShaderCompiler/blob/master/inc/Xsc/Targets.h#L67) to let Xsc find the lowest possible GLSL output version for you.

**Comment by moradin** [comment]
It works, thanks for the tip. This feature works for me the way it is now but I will leave this request because you mentioned there is something more you are planning to do around it.

**Comment by LukasBanana** [comment]
With the [e0faa95](https://github.com/LukasBanana/XShaderCompiler/commit/e0faa950b040726c0af6d19183421b198c61dd3a) commit, I've added the `--pack-uniforms` command to the shell and respective options for the debugger view.
BTW: the `STL-export-fix` branch is now merged into the master branch.
