### ISSUE TITLE
Feature request: Improve reflection

### ISSUE THREAD

**Issue by moradin** [LukasBanana/XShaderCompiler#89]
I am adding one request with multiple things to keep them in one place. If you prefer separate requests let me know.

The improvements that are necessary for my use cases:
- each constant buffer should have a vector of constants (uniforms) that are contained within
- uniforms should provide information about the data type (float, int, bool, etc...) and the number of values (float, float2, float3, etc...)
- uniforms contained in constant buffers should provide information about their byte offsets within the buffer (taking into consideration the packing)
- all resources and constants should provide information if they are used in the currently compiled shader or not
- input attributes should provide information about both the original HLSL name and the original usage of the input semantic (while keeping the provided info about the GLSL name)

**Comment by LukasBanana** [comment]
I won't have time for this until in two weeks. Nevertheless, I think these are some reasonable features you requested.

For now, you can maybe use the compiler twice:
1. Only analyze the code without the packing to get the uniforms.
2. Do the actual compilation process without reflection.

**Comment by moradin** [comment]
Unfortunately this is not a viable solution because I still don't get the data type, width and byte offset. For now I need to reuse the reflection information from the HLSL compiler somehow

**Comment by LukasBanana** [comment]
I'll think about improving the shader reflection in a broader range, but in two weeks at the earliest.

**Comment by mafiesto4** [comment]
Maybe you could use this: https://github.com/FlaxEngine/XShaderCompiler/commit/3ef0376b4aaff5dfd76fb1a007ccf829c10e19a5 with some tweaks. Flax uses uniform buffers reflection to calculate their size.

**Comment by LukasBanana** [comment]
I've already seen your extended code reflection. Looks pretty solid, but I think I will try a more generic approach that also gathers the byte offset within a constant buffer including its padding. Gathering the padding size of a constant buffer (as available with [`Xsc::Reflection::ConstantBuffer::padding`](https://github.com/LukasBanana/XShaderCompiler/blob/master/inc/Xsc/Reflection.h#L240)) is not trivial but I already started with its implementation in the AST classes.

**Comment by LukasBanana** [comment]
Today I started with the design of the new public interfaces for a richer code reflection. I think this is going into the right direction. Have a look at [42311da](https://github.com/LukasBanana/XShaderCompiler/commit/42311dacfc46186bf694836ab074df88171150e7) and let me know what you think about it.

The new structs of importance are `Field` (for data members) and `Record` (for structures). I chose these terms that are commonly known in computer science, to avoid overlapping names with the syntax across C, C++, and C#.

Each `ConstantBuffer` and `Record` has a list of `Field`s. Each `Field` has a data type and an optional index to the global list of `Record`s.

Here is a brief example (pseudocode):
```cs
Xsc.Reflection.ReflectionData reflect;
/* compile and reflect ... */
foreach cbuffer in reflect.constantBuffers {
  foreach field in cbuffer.fields {
    if field.typeRecordIndex >= 0 {
      // get record type of this field:
      recordTypeOfThisField = reflect.records[field.typeRecordIndex]
      /* ... */
    }
  }
}
```

**Comment by moradin** [comment]
Looks good as a start! 
Please keep in mind that this should work together with the uniform packing feature.

**Comment by LukasBanana** [comment]
Done with [e0789bc](https://github.com/LukasBanana/XShaderCompiler/commit/e0789bcfef2b44a3f2b15f5f5437379ba2ac0fc9).
The first test looks good so far. Some feedback on this is appreciated.

**Comment by moradin** [comment]
I won't be able to check this with the original data I used because I've moved on from the project where I was using it, unfortunately.

**Comment by LukasBanana** [comment]
If there is something else regarding reflection, just re-open the ticket (or a new one).
