### ISSUE TITLE
Open source DirectX Shader Compiler

### ISSUE THREAD

**Issue by Jjagg** [LukasBanana/XShaderCompiler#9]
Just a heads up that Microsoft just released an open source DX shader compiler. 
https://github.com/Microsoft/DirectXShaderCompiler

That may be of interest to this project :)

**Comment by LukasBanana** [comment]
This is indeed of interest, thanks for sharing.
I've heard of that MS will open source its HLSL Compiler, but didn't found the project until yet.

The official MS compiler is of course more reliable, and using its IR to translate to another backend is also a good approach for cross-compiling shaders.

However, I think there are still good reasons for a direct _High-Level-to-High-Level_ Translation approach.
One of this is to keep the entire program structure (also function and variable names), which makes maintaining the cross-compiled shader more convenient (i.e. GLSL or Metal SL).
Generting GLSL from an IR might generate some entire differently structured program.
