### ISSUE TITLE
Include only shader throws an exception

### ISSUE THREAD

**Issue by moradin** [LukasBanana/XShaderCompiler#90]
I think I stumbled upon an edge case. I have a shader that basically just includes another shader like this:

`#include <other_shader.hlsl>`

This shader fails parsing in PreProcessor::Process() and throws the following exceptions:

```
Exception thrown at 0x00007FF92430A388: Microsoft C++ exception: std::runtime_error at memory location 0x00000054CF3D5400.
Exception thrown at 0x00007FF92430A388: Microsoft C++ exception: Xsc::Report at memory location 0x00000054CF3D2A50.
```

**Comment by LukasBanana** [comment]
I can't reproduce this issue without more information.
What does the `other_shader.hlsl` file look like and what are the compiler options?

I just tried `xsc -PP -Valid include_test.hlsl` where the input file only includes an empty `other_shader.hlsl` file.
Nothing problamatic happens.

**Comment by moradin** [comment]
You are right it's probably not related to that. I was digging into this a bit deeper and I think the issue is that I haven't found a way to set the defines we use on the HLSL compiler side. The HLSL compiler has a parameter that accepts an arbitrary list of defines, I can't see anything similar in XShaderCompiler at the moment. Am I just missing it somehow?

**Comment by LukasBanana** [comment]
Do you mean to just add pre-defined macros like in GCC with `gcc -Dfoobar=1`,
which is basically `#define foobar 1`?

Xsc has the same command line option but when you're using the library you just have to add it before your source code:
```cpp
std::stringstream inputCode;
inputCode << "#define foobar 1\n";
inputCode << myActualCodeString;
```

**Comment by moradin** [comment]
I'm specifically talking about the pDefines parameter of [D3DXCompileShader](https://docs.microsoft.com/en-us/windows/desktop/direct3d9/d3dxcompileshader).
You are right that I can add it to the string, I was just wondering if there is a more elegant solution.
