### ISSUE TITLE
The order of defines changes the results

### ISSUE THREAD

**Issue by moradin** [LukasBanana/XShaderCompiler#94]
I don't know if this is covered by the standard or not but I have big issues with the way defines are handled.

Example code here:
http://shader-playground.timjones.io/54126c67c59ce2c55e36b13da4a165dd

Try changing the order of the defines and it will compile fine.

The problem is that I can't change the order because the first define comes from the "command line" which I just prepend to the shader based on your previous suggestion. The second define is coming from an include.

FXC happily compiles this.

**Comment by LukasBanana** [comment]
Thanks for pointing that out. I'm very unhappy about this, but it seems you're right. Macro expansion is more complicated than I thought when I started with this project. However, the macro expansion in HLSL is also not identical with the one in MSVC, and I never found a specification for it either.

**Comment by LukasBanana** [comment]
Fixed with [6a8bcef](https://github.com/LukasBanana/XShaderCompiler/commit/6a8bcef8510f25ab9fa1bd38947e3ad4e7b6dce7).
