### ISSUE TITLE
Arrays in input structures generate invalid GLSL

### ISSUE THREAD

**Issue by moradin** [LukasBanana/XShaderCompiler#95]
This is a really rarely used thing in HLSL but it is possible to write a shader like this:
http://shader-playground.timjones.io/1cb288adefd74228d8783729969fb3b9

Unfortunately the generated GLSL is not valid

**Comment by LukasBanana** [comment]
The translation of structures in input and output semantics is very tricky when operating solely on the AST. This is also why translation of structures that are used as both input *and* output does not work, too.

**Comment by LukasBanana** [comment]
I'm working on this project again, and this issue was actually quite a small one.
Fixed with [1f6c02c](https://github.com/LukasBanana/XShaderCompiler/commit/1f6c02c3b888e3151dfb771bb401fc0403d3ed56).
